name: Build Firefox Extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install web-ext
      run: npm install --global web-ext

    - name: Build Firefox Extension
      run: |
        cd firefox
        web-ext build

    - name: Sign extension
      run: |
        cd firefox
        web-ext sign --api-key="${{ secrets.KEY }}" --api-secret="${{ secrets.VALUE }}"
      env:
        WEB_EXT_SOURCE_DIR: ./firefox

    - name: Upload signed artifact
      uses: actions/upload-artifact@v4
      with:
        name: pwnfox-signed-extension
        path: firefox/web-ext-artifacts/*.xpi
