name: Build Firefox Extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install web-ext
      run: npm install --global web-ext

    - name: Build Firefox Extension
      run: |
        cd firefox
        web-ext build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: firefox/web-ext-artifacts/*.zip
